# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import service_pb2 as proto_dot_service__pb2


class AnalyzerEntityStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.sendFileToAnalyze = channel.stream_unary(
                '/AnalyzerEntity/sendFileToAnalyze',
                request_serializer=proto_dot_service__pb2.DataFile.SerializeToString,
                response_deserializer=proto_dot_service__pb2.FileAck.FromString,
                )
        self.GetAnalyzerResults = channel.unary_stream(
                '/AnalyzerEntity/GetAnalyzerResults',
                request_serializer=proto_dot_service__pb2.Request.SerializeToString,
                response_deserializer=proto_dot_service__pb2.AnalyzerResults.FromString,
                )


class AnalyzerEntityServicer(object):
    """Missing associated documentation comment in .proto file."""

    def sendFileToAnalyze(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAnalyzerResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalyzerEntityServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'sendFileToAnalyze': grpc.stream_unary_rpc_method_handler(
                    servicer.sendFileToAnalyze,
                    request_deserializer=proto_dot_service__pb2.DataFile.FromString,
                    response_serializer=proto_dot_service__pb2.FileAck.SerializeToString,
            ),
            'GetAnalyzerResults': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAnalyzerResults,
                    request_deserializer=proto_dot_service__pb2.Request.FromString,
                    response_serializer=proto_dot_service__pb2.AnalyzerResults.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AnalyzerEntity', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AnalyzerEntity(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def sendFileToAnalyze(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/AnalyzerEntity/sendFileToAnalyze',
            proto_dot_service__pb2.DataFile.SerializeToString,
            proto_dot_service__pb2.FileAck.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAnalyzerResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/AnalyzerEntity/GetAnalyzerResults',
            proto_dot_service__pb2.Request.SerializeToString,
            proto_dot_service__pb2.AnalyzerResults.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
